### ISSUE TITLE
Bài #35: Sharing state between steps [#option]

### ISSUE THREAD

**Issue by Jacobvu84** [Jacobvu84/serenity-pageobject-junit-webdriver#35]
- [Share information between steps](https://johnfergusonsmart.com/sharing-state-steps-serenity-bdd/)
- [How to keep Serenity Variable Session](https://github.com/serenity-bdd/serenity-core/issues/1748)

**Comment by Jacobvu84** [comment]
Video hướng dẫn cho việc sử dụng [Serenity Session](http://www.youtube.com/watch?v=KnrRVfwbkwQ)

**Comment by Jacobvu84** [comment]
Những điều chú ý:
- Đối với serenity session variable thì giá trị của nó không bị reset sau khi mỗi scenario kết thúc, cũng không bị reset khi một Class test kết thúc.

- Đối với @share = true thì giá trị của nó không bị reset sau khi mỗi scenario kết thúc nhưng sẽ bị reset khi mỗi class test kết thúc. 

Lưu ý khi chạy song song thì không nên thiết sử dụng chức năng này. Nó sẽ gây lẫn lộn dữ liệu giữa các thread.

**Comment by ntthaibk** [comment]
Thanks anh nhiều ạ, randomly search được solution để share state ở đây :D
